### ISSUE TITLE
installatie faalt. File.php does not exists

### ISSUE THREAD

**Issue by hans2103** [magehost/magehost_blockcache#2]
Bij installatie via composer verschijnt de volgende foutmelding

```
  [ErrorException]                                                                                                                                             
  Source /data/ssd/vhosts/staging.babyandmore.eu/source/vendor/magehost/magehost_blockcache/app/code/community/MageHost/Cm/Cache/Backend/File.php does not ex  
  ist 
```

Doorloop ik de directorystructuur van deze repo, dan zie ik dat de directory Backend een submodule is en uitkomt bij https://github.com/magehost/magehost_cm_cache_backend/tree/701d7e82093d20cf94adf41ea5a1db9a2161080f

het komt niet uit bij
https://github.com/magehost/magehost_cm_cache_backend

Laatstgenoemde bevat wel een composer.json, eerstgenoemde niet. Geen idee of dat er iets mee te maken heeft.

**Comment by jeroenvermeulen** [comment]
@hans2103 Just pushed update b8b2f4a, please test again.

**Comment by cjprinse** [comment]
De installatie faalt ook bij een composer install, met dezelfde melding

**Comment by jeroenvermeulen** [comment]
There is no good solution for Git Submodules + Composer install (yet).
While submodules are the preferred solution for Modman.

I updated the submodules, now when I navigate to `app/code/community/MageHost/Cm/Cache/Backend` in GitHub I end up here:
https://github.com/magehost/magehost_cm_cache_backend/tree/768b4e8015159ca780fe68b62b6913a7e997b6bc

When I navigate to `app/code/community/Cm/Cache/Backend` I go to:
https://github.com/colinmollenhour/Cm_Cache_Backend_File/tree/51251b80a817790eb624fbe2afc882c14f3c4fb0

Both places contain a `composer.json`.
