### ISSUE TITLE
double entry in magento modules list

### ISSUE THREAD

**Issue by cjprinse** [magehost/magehost_blockcache#3]
In the modules list, there is an MageHost_BlockCache and a magehost_blockcache.

When you change MageHost_BlockCache to magehost_blockcache in /etc/modules/MageHost_BlockCache.xml, this is solved. This xml file is a symlink to the original file in the vendor folder of the application, which is downloaded from this repo (dev-master).

**Comment by jeroenvermeulen** [comment]
Thank you for you contribution @cjprinse. We will test this and apply the change.

**Comment by jeroenvermeulen** [comment]
Fixed in 0525b84b22f3b524a651b7a36fc756ef7d01e6cf
